account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.edit_profile, name='profile_edit'),
    path('logout/', views.logout, name='logout'),
    path('', views.login, name='login'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('katalog/', include('katalog.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

katalog/urls.py
from django.urls import path
from . import views

app_name = 'katalog'

urlpatterns = [
    path('upload/', views.upload_book, name='upload-book'),
    path('<int:book_id>/', views.book_detail, name='book-detail'),
    path('<int:book_id>/edit/', views.book_edit, name='book-edit'),
    path('book/<int:book_id>/delete/', views.delete_book, name='delete-book'),
    path('book/<int:pk>/toggle-favorite/', views.toggle_favorite, name='toggle-favorite'),
    path('book/<int:book_id>/preview/', views.book_preview, name='book-preview'),
    path('books/<int:book_id>/analyze/', views.analyze_book, name='analyze_book'),
    path('favorites/', views.favorite_books, name='favorite-book'),
    path('', views.BookListView.as_view(), name= 'book-list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'katalog:book-list' %}">Ebook</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'katalog:book-list' %}">Katalog</a>
              <a class="nav-link" href="{% url 'katalog:favorite-book' %}">Favorit</a>
              <a class="nav-link" href="{% url 'account:profile' %}">Profil</a>
            </div>
          </div>

          <form class="d-flex" role="search" action="{% url 'katalog:book-list' %}" method="get">
            <input class="form-control me-2" type="search" name="query" placeholder="Search by title, year, or description" aria-label="Search" value="{{ request.GET.query }}">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        
          <a href="{% url 'katalog:upload-book' %}" class="btn btn-outline-primary ms-2">Upload</a>
          <a class="nav-link ml-3" href="{% url 'account:logout' %}" style="margin-left: 10px; color: red">Keluar</a>

        </div>

      </nav>

      {% if user.is_authenticated %}
      {% else %}
        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
      {% endif %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

  </body>
</html>